---
- name: Permanently disable SELINUX
  selinux: state=disabled

- name: Refresh setup facts
  setup:

- name: Restart node
  debug:
    msg: 'SELinux MUST be disabled, selinux has been updated, restarting node now...'
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"

- name: Restarting node now
  ignore_errors: yes
  become: yes
  shell: 'reboot now'
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"
  async: 0
  poll: 0

- name: Waiting for server to complete restarting
  become: no
  local_action: wait_for host='{{ ansible_host }}' state=started delay=60 timeout='{{ server_restart_timeout }}'
  when: "{{ ansible_selinux.status | lower != 'disabled' and (server_restart is defined and server_restart | bool )}}"

- name: Server usually needs a little more time ...
  become: no
  local_action: wait_for host='{{ ansible_host }}' state=started delay=30
  when: "{{ ansible_selinux.status | lower != 'disabled' and (server_restart is defined and server_restart | bool )}}"
