---
- name: Permanently disable SELINUX
  selinux: state=disabled

- name: Refresh setup facts
  setup:

- name: Restart node
  fail:
    msg: 'SELinux MUST be disabled, selinux has been updated, restarting node now...'
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"

#- name: Restarting node now
#  ignore_errors: yes
#  become: yes
#  shell: 'reboot now'
#  when: "{{ ansible_selinux.status | lower != 'disabled' }}"
#  async: 0
#  poll: 0

#  Requires sudo on the control server
#- name: Waiting for server to complete reboot cycle
#  local_action: wait_for port='{{ ansible_port }}' state=started

