---
# tasks file for opdk-setup-selinux-disable
- name: Permanently disable SELINUX
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^(SELINUX=)"
    line: '\1disabled'
    backrefs: yes
    backup: yes
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"

- name: Refresh setup facts
  setup:

- name: Restart node
  debug:
    msg: 'SELinux MUST be disabled, selinux has been updated, restarting node now...'
  when: "{{ ansible_selinux.status | lower != 'disabled' }}"

- block:

  - name: Restarting node now
    become: true
    ignore_errors: yes
    shell: 'reboot now'
    when: "{{ ansible_selinux.status | lower != 'disabled' }}"
    async: 45
    poll: 0

  rescue:

  - name: Waiting for node to return
    local_action: wait_for state=started host='{{ inventory_host }}' port=22
